- name: creating ec2_instances
  hosts: localhost
  connection: local
  become: yes

  vars:
  - ami_id: ami-09c813fb71547fc4f
    sg_id: sg-031c227c91b0f22ac
    zone_id: Z07584893CQK1749AT0H4
    domine_name: lylbwof.xyz
    instances: 
    - mongodb
  tasks:
  - name: creating ec2_instances
    amazon.aws.ec2-instance:
      name: "{{ items }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ items }}"
  loop: "{{ instances }}"
  register: ec2_output

  - name: print ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"