- name: creating instances
  hosts: localhost
  connection: local
  become: yes

  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-031c227c91b0f22ac 
    zone_id: Z07584893CQK1749AT0H4
    domaine_id: lylbwof.xyz
    instances:
    - nginx
    - mongodb
  
  tasks:
  - name: creating ec2_instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  # - name: print ec2_public_ip_address
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output_results }}"

  # - name: print ec2_private_ip_address
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output_results }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domaine_name }}"
      record: "{{ item.item }}.{{ domaine_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output_results }}"

