- name: play level variables
  hosts: local
  connection: localhost
  vars:
    - name: "santhosh tonanki"
      age: 29
      course: "Ansible"
      duration: "5 hours"
      Trainer: "sivakumar reddy"
  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: " hello world my name is {{ Name }}, and my age is {{ Age }} and my course is {{ Course }}, duration is {{ Duration }}, and my trainer is {{ Trainer }}"

- name: second play with different variables
  hosts: local
  connection: localhost
  vars:
    - name: "Bantupalli Gangayya"
      age: 28
      course: "DevOps"
      duration: "1 hour"
      Trainer: "sivakumar reddy"
  tasks:
    - name: print the course information
      ansible.builtin.debug:
        msg: " hello world my name is {{ Name }}, and my age is {{ Age }} and my course is {{ Course }}, duration is {{ Duration }}, and my trainer is {{ Trainer }}"
   