
- name: variables from args
  hosts: localhost
  connection: local
  tasks:
  - name: print credintials
    ansbile.builtin.debug:
      msg: "person_name is {{ person_name }}, age is {{ age }}, course name is {{ course }}, duration is {{ duration }}, trainer is {{ trainer }}."
