- name: variables from preferences
  hosts: localhost
  connection: local
  vars: 
    NAME: preference from play level
  vars_files:
  - course.yaml
  vars_prompt: 
  - name: "NAME"
    prompt: "what is your NAME?"
    private: "no"
  tasks:
  - name: testing variables preference
    # vars: 
    #   NAME: preference from task level
    # ansible.builtin.debug:
    #   msg: "Name is {{ NAME }}"
