- name: conditions with yaml
  hosts: localhost
  connection: local
  vars:
    Number: 9
  tasks:
    - name: check the number is less than 10 or not
      ansible.builtin.debug:
        msg: "Given number {{ Number }} is less than 10"
      when: Number < 10