- name: checking facts
  hosts: localhost
  connections: local
  become: yes
  tasks:
  - name: "install nginx if RedHat"
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family == "RedHat"

  - name: "install nginx if RedHat"
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family == "Debian"
