- name: checking facts
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: "install nginx if RedHat"
    ansible.builtin.dnf:
      name: nginx
      state: prasent

  - name: "start nginx if RedHat"
    ansible.builtin.service:
      name: "nginx"
      state: "started"
      enabled: yes
    when: ansible_os_family == "RedHat"

  - name: "install nginx if Debian"
    ansible.builtin.apt:
      name: nginx
      state: prasent

  - name: "start nginx if Debian"
    ansible_builtin.service:
      name: nginx
      state: "start"
      enabled: yes
    when: ansible_os_family == "Debian"
