- name: checking facts
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: install nginx if RedHat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: start nginx if RedHat
    ansible.builtin.service:
      name: nginx
      state: started
      private: yes
    when: ansible_os_family == "RedHat"

  - name: install nginx if Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"   

  - name: start nginx if Debian
    ansible.builtin.service:
      name: nginx
      state: started
      private: yes
    when: ansible_os_family == "Debian"

    