- name: install packages
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: print package names
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "nginx", state: "absent" }
    - { name: "mysql", state: "absent" } 
    - { name: "zip", state: "latest"}
    