# string changing into list

- name: functions
  hosts: localhost
  connection: local
  become: yes
  vars:
    technologies: "DevOps, ansible, kubernates, shellscript, jenking, cicd, docker, terraform" # this is a string
  tasks:
  - name: print string to list
    ansible.builtin.debug:
      msg: "Hello! your list is {{ technologies | split(',') }} "

# string to list
# we can make a list without creating "vars". 
# instead of "vars" we an write in "msg". like "msg: "hello your list is {{ DevOps, ansible, kubernates, shellscript, jenking, cicd, docker, terraform | split(',') }}"